### ISSUE TITLE
the sample is empty, is there any java and obj-c or swift sample?

### ISSUE THREAD

**Issue by bitcard** [synonymdev/react-native-libsodium#10]

**Comment by Jasonvdb** [comment]
There is an example project: https://github.com/synonymdev/react-native-libsodium/tree/main/example

It's a react native package so there isn't any sample the obj-c and java code. The [obj-c](https://github.com/synonymdev/react-native-libsodium/tree/main/ios/RCTSodium) and [java](https://github.com/synonymdev/react-native-libsodium/tree/main/android/src/main/java/com/reactnativelibsodium) is just for interfacing between the JS code and the native c libraries.

**Comment by bitcard** [comment]
> obj-c

thank you, I will try to use the interface.
